#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 OpenWrt.org
# Put this inside /etc/init.d/

START=91
STOP=10
USE_PROCD=1


start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 \
        /root/klipper/klippy/klippy.py \
        /root/klipper_config/printer.cfg -l /root/klipper_logs/klippy.log -a /tmp/klippy_uds
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

